name: CI/CD Mini Chat

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Vérifier le code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Build backend Docker image
      - name: Build Backend
        run: docker build -t tp-examen-chat ./Backend

      # 3. Build frontend Docker image
      - name: Build Frontend
        run: docker build -t tp-examen-chat ./Frontend

      # 4. Lister les images Docker pour vérification
      - name: List Docker images
        run: docker images
